server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating_micro
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect